//IE 11 does not support ligatures so we need a cross-reference from material icon name to corresponding unicode character.
export const materialIconsXref = {
    menu: '\ue5d2',
    public: '\ue80b',
    today: '\ue8df',
    date_range: '\ue916',
    event_note: '\ue616',
    save: '\ue161',
    content_copy: '\ue14d',
    delete: '\ue872',
    attach_file: '\ue226',
    check_box: '\ue834',
    check_box_outline_blank: '\ue835',
    home: '\ue88a',
    flight_takeoff: '\ue905',
    cloud_download: '\ue2c0',
    videogame_asset: '\ue338',
    send: '\ue163',
    drafts: '\ue151',
    grade: '\ue838',
    inbox: '\ue156',
    person: '\ue7ff',
    arrow_drop_down: '\ue5c5',
    arrow_drop_up: '\ue5c7',
    drag_handle: '\ue25d',
    restore_page: '\ue929',
    keyboard_arrow_down: '\ue313',
    keyboard_arrow_up: '\ue316',
    android: '\ue859',
    check: '\ue5ca',
    search: '\ue8b6'
};
