import React from 'react';
import ReactDOM from 'react-dom';
import { Table, TableBody, TableFooter, TableHeader, TableHeaderColumn, TableRow, TableRowColumn } from 'material-ui/Table';
import TextField from 'material-ui/TextField';
import Toggle from 'material-ui/Toggle';
import 'react-select/dist/react-select.css';
import Select from 'react-select';
import Option from 'react-select';
import Highlighter from 'react-highlight-words';
import { amber400 } from 'material-ui/styles/colors';

const options = [
        { code: '743', description: '00000001TEST', closeDate: '' },
        { code: '741', description: '00001TEST', closeDate: '' },
        { code: '778', description: '111', closeDate: '' },
        { code: '726', description: '1111', closeDate: '' },
        { code: '779', description: '112', closeDate: '' },
        { code: '443', description: '122222', closeDate: '' },
        { code: '869', description: '12345', closeDate: '' },
        { code: '841', description: '12345ABC', closeDate: '' },
        { code: '997', description: '144136', closeDate: '' },
        { code: '902', description: '144350', closeDate: '' },
        { code: '879', description: '154386', closeDate: '' },
        { code: '946', description: '1559', closeDate: '' },
        { code: '1506', description: '1560', closeDate: '' },
        { code: '905', description: '164126', closeDate: '' },
        { code: '939', description: '164170', closeDate: '' },
        { code: '991', description: '164368', closeDate: '' },
        { code: '1863', description: '164369', closeDate: '' },
        { code: '992', description: '164370', closeDate: '' },
        { code: '151', description: '172AE', closeDate: '' },
        { code: '998', description: '174142', closeDate: '' },
        { code: '1860', description: '174387', closeDate: '' },
        { code: '1861', description: '174388', closeDate: '' },
        { code: '363', description: '178CB', closeDate: '' },
        { code: '72', description: '179CB', closeDate: '' },
        { code: '152', description: '183AE', closeDate: '' },
        { code: '71', description: '183CB', closeDate: '' },
        { code: '887', description: '184116', closeDate: '' },
        { code: '897', description: '184120', closeDate: '' },
        { code: '908', description: '184129', closeDate: '' },
        { code: '906', description: '184131', closeDate: '' },
        { code: '907', description: '184132', closeDate: '' },
        { code: '943', description: '184172', closeDate: '' },
        { code: '937', description: '184178', closeDate: '' },
        { code: '990', description: '184184', closeDate: '' },
        { code: '940', description: '184187', closeDate: '' },
        { code: '942', description: '184188', closeDate: '' },
        { code: '1824', description: '184192', closeDate: '' },
        { code: '994', description: '184209', closeDate: '' },
        { code: '938', description: '184294', closeDate: '' },
        { code: '941', description: '184295', closeDate: '' },
        { code: '1862', description: '184296', closeDate: '' },
        { code: '1812', description: '184297', closeDate: '' },
        { code: '1815', description: '184298', closeDate: '' },
        { code: '993', description: '184299', closeDate: '' },
        { code: '1813', description: '184300', closeDate: '' },
        { code: '1814', description: '184301', closeDate: '' },
        { code: '1816', description: '184302', closeDate: '' },
        { code: '995', description: '184374', closeDate: '' },
        { code: '927', description: '184380', closeDate: '' },
        { code: '999', description: '184556', closeDate: '' },
        { code: '153', description: '186AE', closeDate: '' },
        { code: '936', description: '187177', closeDate: '' },
        { code: '154', description: '187AE', closeDate: '' },
        { code: '2049', description: '187AE', closeDate: '' },
        { code: '1214', description: '187V', closeDate: '' },
        { code: '162', description: '194CB', closeDate: '' },
        { code: '2', description: '2', closeDate: '' },
        { code: '926', description: '204147', closeDate: '' },
        { code: '2192', description: '20608190', closeDate: '' },
        { code: '2177', description: '20608209', closeDate: '' },
        { code: '2187', description: '20608210', closeDate: '' },
        { code: '2189', description: '20608211', closeDate: '' },
        { code: '2180', description: '20608212', closeDate: '' },
        { code: '2193', description: '20608213', closeDate: '' },
        { code: '2185', description: '20608219', closeDate: '' },
        { code: '2183', description: '20608231', closeDate: '' },
        { code: '2190', description: '20608232', closeDate: '' },
        { code: '2184', description: '20608236', closeDate: '' },
        { code: '2188', description: '20608239', closeDate: '' },
        { code: '2186', description: '20608245', closeDate: '' },
        { code: '2181', description: '20608248', closeDate: '' },
        { code: '2191', description: '20608249', closeDate: '' },
        { code: '2182', description: '20608251', closeDate: '' },
        { code: '911', description: '214128', closeDate: '' },
        { code: '901', description: '214247', closeDate: '' },
        { code: '917', description: '214267', closeDate: '' },
        { code: '967', description: '214269', closeDate: '' },
        { code: '986', description: '214500', closeDate: '' },
        { code: '987', description: '214501', closeDate: '' },
        { code: '996', description: '214502', closeDate: '' },
        { code: '1864', description: '214503', closeDate: '' },
        { code: '1865', description: '214504', closeDate: '' },
        { code: '1866', description: '214505', closeDate: '' },
        { code: '1002', description: '214506', closeDate: '' },
        { code: '988', description: '214507', closeDate: '' },
        { code: '989', description: '214508', closeDate: '' },
        { code: '1881', description: '214509', closeDate: '' },
        { code: '1882', description: '214510', closeDate: '' },
        { code: '1883', description: '214511', closeDate: '' },
        { code: '1887', description: '214512', closeDate: '' },
        { code: '1889', description: '214513', closeDate: '' },
        { code: '1896', description: '214514', closeDate: '' },
        { code: '1826', description: '214515', closeDate: '' },
        { code: '1825', description: '214517', closeDate: '' },
        { code: '1893', description: '214518', closeDate: '' },
        { code: '1894', description: '214519', closeDate: '' },
        { code: '2166', description: '214520', closeDate: '' },
        { code: '1902', description: '214521', closeDate: '' },
        { code: '2134', description: '214522', closeDate: '' },
        { code: '2145', description: '214523', closeDate: '' },
        { code: '2143', description: '214524', closeDate: '' },
        { code: '2165', description: '214526', closeDate: '' },
        { code: '2140', description: '214528', closeDate: '' },
        { code: '2142', description: '214529', closeDate: '' },
        { code: '2067', description: '214530', closeDate: '' },
        { code: '2147', description: '214532', closeDate: '' },
        { code: '2168', description: '214533', closeDate: '' },
        { code: '2169', description: '214534', closeDate: '' },
        { code: '3163', description: '214555', closeDate: '' },
        { code: '704', description: '2223412', closeDate: '' },
        { code: '1000', description: '224274', closeDate: '' },
        { code: '882', description: '224386', closeDate: '' },
        { code: '402', description: '22718', closeDate: '' },
        { code: '364', description: '23', closeDate: '' },
        { code: '399', description: '230CB', closeDate: '' },
        { code: '703', description: '23213322 GTF', closeDate: '' },
        { code: '860', description: '23213322 GTF A', closeDate: '' },
        { code: '309', description: '23321', closeDate: '' },
        { code: '1046', description: '233326', closeDate: '' },
        { code: '310', description: '23344', closeDate: '' },
        { code: '311', description: '23350', closeDate: '' },
        { code: '312', description: '23423', closeDate: '' },
        { code: '931', description: '234264', closeDate: '' },
        { code: '972', description: '234265', closeDate: '' },
        { code: '1868', description: '234266', closeDate: '' },
        { code: '1869', description: '234272', closeDate: '' },
        { code: '970', description: '234278', closeDate: '' },
        { code: '973', description: '234279', closeDate: '' },
        { code: '916', description: '234280', closeDate: '' },
        { code: '900', description: '234283', closeDate: '' },
        { code: '963', description: '234285', closeDate: '' },
        { code: '934', description: '234287', closeDate: '' },
        { code: '890', description: '234288', closeDate: '' },
        { code: '904', description: '234289', closeDate: '' },
        { code: '971', description: '234291', closeDate: '' },
        { code: '968', description: '234292', closeDate: '' },
        { code: '924', description: '234306', closeDate: '' },
        { code: '965', description: '234307', closeDate: '' },
        { code: '966', description: '234308', closeDate: '' },
        { code: '909', description: '234309', closeDate: '' },
        { code: '977', description: '234310', closeDate: '' },
        { code: '978', description: '234327', closeDate: '' },
        { code: '979', description: '234329', closeDate: '' },
        { code: '980', description: '234331', closeDate: '' },
        { code: '969', description: '234337', closeDate: '' },
        { code: '981', description: '234348', closeDate: '' },
        { code: '921', description: '234349', closeDate: '' },
        { code: '1001', description: '234353', closeDate: '' },
        { code: '975', description: '234358', closeDate: '' },
        { code: '974', description: '234362', closeDate: '' },
        { code: '918', description: '234375', closeDate: '' },
        { code: '891', description: '235125', closeDate: '' },
        { code: '316', description: '23747', closeDate: '' },
        { code: '277', description: '241CB', closeDate: '' },
        { code: '357', description: '2423S', closeDate: '' },
        { code: '336', description: '243DR', closeDate: '' },
        { code: '317', description: '24548', closeDate: '' },
        { code: '1174', description: '24558', closeDate: '' },
        { code: '320', description: '24641', closeDate: '' },
        { code: '321', description: '2531K', closeDate: '' },
        { code: '1049', description: '253261', closeDate: '' },
        { code: '888', description: '254102', closeDate: '' },
        { code: '925', description: '254103', closeDate: '' },
        { code: '935', description: '254123', closeDate: '' },
        { code: '886', description: '254150', closeDate: '' },
        { code: '914', description: '254152', closeDate: '' },
        { code: '912', description: '254225', closeDate: '' },
        { code: '915', description: '254248', closeDate: '' },
        { code: '976', description: '254290', closeDate: '' },
        { code: '985', description: '254305', closeDate: '' },
        { code: '961', description: '254311', closeDate: '' },
        { code: '899', description: '254312', closeDate: '' },
        { code: '928', description: '254313', closeDate: '' },
        { code: '893', description: '254314', closeDate: '' },
        { code: '889', description: '254315', closeDate: '' },
        { code: '892', description: '254316', closeDate: '' },
        { code: '885', description: '254317', closeDate: '' },
        { code: '962', description: '254318', closeDate: '' },
        { code: '1870', description: '254319', closeDate: '' },
        { code: '1799', description: '254320', closeDate: '' },
        { code: '1800', description: '254321', closeDate: '' },
        { code: '1872', description: '254322', closeDate: '' },
        { code: '1871', description: '254323', closeDate: '' },
        { code: '982', description: '254324', closeDate: '' },
        { code: '1859', description: '254325', closeDate: '' },
        { code: '2144', description: '254338', closeDate: '' },
        { code: '883', description: '254339', closeDate: '' },
        { code: '983', description: '254340', closeDate: '' },
        { code: '984', description: '254341', closeDate: '' },
        { code: '964', description: '254342', closeDate: '' },
        { code: '932', description: '254355', closeDate: '' },
        { code: '1773', description: '254360', closeDate: '' },
        { code: '895', description: '254366', closeDate: '' },
        { code: '1904', description: '254383', closeDate: '' },
        { code: '930', description: '254384', closeDate: '' },
        { code: '933', description: '254385', closeDate: '' },
        { code: '876', description: '254386', closeDate: '' },
        { code: '919', description: '254901', closeDate: '' },
        { code: '735', description: '2653PTDRIVE', closeDate: '' },
        { code: '884', description: '267A', closeDate: '' },
        { code: '325', description: '2734K', closeDate: '' },
        { code: '896', description: '274273', closeDate: '' },
        { code: '894', description: '274276', closeDate: '' },
        { code: '920', description: '274277', closeDate: '' },
        { code: '903', description: '274303', closeDate: '' },
        { code: '913', description: '274304', closeDate: '' },
        { code: '898', description: '274343', closeDate: '' },
        { code: '1873', description: '274345', closeDate: '' },
        { code: '929', description: '274361', closeDate: '' },
        { code: '1804', description: '284139', closeDate: '' },
        { code: '3', description: '3', closeDate: '' },
        { code: '910', description: '303329', closeDate: '' },
        { code: '2035', description: '324EB', closeDate: '' },
        { code: '33', description: '33', closeDate: '' },
        { code: '3177', description: '33-DB-TEST', closeDate: '' },
        { code: '950', description: '332104', closeDate: '' },
        { code: '874', description: '332114', closeDate: '' },
        { code: '853', description: '332116', closeDate: '' },
        { code: '875', description: '332121', closeDate: '' },
        { code: '3185', description: '3333-11', closeDate: '' },
        { code: '3186', description: '3333-22', closeDate: '' },
        { code: '444', description: '33333', closeDate: '' },
        { code: '1196', description: '333391', closeDate: '' },
        { code: '34', description: '34', closeDate: '' },
        { code: '742', description: '3456', closeDate: '' },
        { code: '117', description: '3538R', closeDate: '' },
        { code: '770', description: '3552', closeDate: '' },
        { code: '755', description: '360INCV2', closeDate: '' },
        { code: '662', description: '369', closeDate: '' },
        { code: '37', description: '37', closeDate: '' },
        { code: '413', description: '371HS', closeDate: '' },
        { code: '400', description: '372HS', closeDate: '' },
        { code: '401', description: '373HS', closeDate: '' },
        { code: '74', description: '376HS', closeDate: '' },
        { code: '84', description: '377HS', closeDate: '' },
        { code: '83', description: '378HS', closeDate: '' },
        { code: '38', description: '38', closeDate: '' },
        { code: '880', description: '382901', closeDate: '' },
        { code: '877', description: '382903', closeDate: '' },
        { code: '39', description: '39', closeDate: '' },
        { code: '881', description: '392771', closeDate: '' },
        { code: '948', description: '392777', closeDate: '' },
        { code: '1056', description: '392778', closeDate: '' },
        { code: '944', description: '392795', closeDate: '' },
        { code: '947', description: '392797', closeDate: '' },
        { code: '90', description: '3930A', closeDate: '' },
        { code: '92', description: '3931A', closeDate: '' },
        { code: '94', description: '3933A', closeDate: '' },
        { code: '130', description: '3937A', closeDate: '' },
        { code: '131', description: '3939A', closeDate: '' },
        { code: '133', description: '3940A', closeDate: '' },
        { code: '132', description: '3944A', closeDate: '' },
        { code: '374', description: '3946A', closeDate: '' },
        { code: '138', description: '3947A', closeDate: '' },
        { code: '141', description: '3949A', closeDate: '' },
        { code: '142', description: '3951A', closeDate: '' },
        { code: '375', description: '3953A', closeDate: '' },
        { code: '386', description: '3972A', closeDate: '' },
        { code: '398', description: '3980A', closeDate: '' },
        { code: '190', description: '3983A', closeDate: '' },
        { code: '40', description: '40', closeDate: '' },
        { code: '214', description: '4035W', closeDate: '' },
        { code: '407', description: '4043L', closeDate: '' },
        { code: '191', description: '4048L', closeDate: '' },
        { code: '216', description: '4055L', closeDate: '' },
        { code: '219', description: '4059W', closeDate: '' },
        { code: '217', description: '4068W', closeDate: '' },
        { code: '41', description: '41', closeDate: '' },
        { code: '2150', description: '412810', closeDate: '' },
        { code: '42', description: '42', closeDate: '' },
        { code: '43', description: '43', closeDate: '' },
        { code: '377', description: '448AE', closeDate: '' },
        { code: '45', description: '45', closeDate: '' },
        { code: '150', description: '455AE', closeDate: '' },
        { code: '202', description: '456', closeDate: '' },
        { code: '46', description: '46', closeDate: '' },
        { code: '192', description: '4604U', closeDate: '' },
        { code: '47', description: '47', closeDate: '' },
        { code: '48', description: '48', closeDate: '' },
        { code: '49', description: '49', closeDate: '' },
        { code: '50', description: '50', closeDate: '' },
        { code: '51', description: '51', closeDate: '' },
        { code: '2167', description: '514533', closeDate: '' },
        { code: '173', description: '51824', closeDate: '' },
        { code: '52', description: '52', closeDate: '' },
        { code: '194', description: '5202Y', closeDate: '' },
        { code: '322', description: '5204G', closeDate: '' },
        { code: '198', description: '5204J', closeDate: '' },
        { code: '197', description: '5204P', closeDate: '' },
        { code: '196', description: '5204Y', closeDate: '' },
        { code: '53', description: '53', closeDate: '' },
        { code: '100', description: '5315X', closeDate: '' },
        { code: '54', description: '54', closeDate: '' },
        { code: '411', description: '5416U', closeDate: '' },
        { code: '170', description: '541PB', closeDate: '' },
        { code: '5', description: '545', closeDate: '' },
        { code: '55', description: '55', closeDate: '' },
        { code: '211', description: '5515Y', closeDate: '' },
        { code: '56', description: '56', closeDate: '' },
        { code: '445', description: '560000', closeDate: '' },
        { code: '339', description: '561A', closeDate: '' },
        { code: '367', description: '5655', closeDate: '' },
        { code: '449', description: '56789', closeDate: '' },
        { code: '57', description: '57', closeDate: '' },
        { code: '58', description: '58', closeDate: '' },
        { code: '59', description: '59', closeDate: '' },
        { code: '157', description: '593PC', closeDate: '' },
        { code: '351', description: '6084W', closeDate: '' },
        { code: '186', description: '6087C', closeDate: '' },
        { code: '353', description: '6088B', closeDate: '' },
        { code: '189', description: '6093K', closeDate: '' },
        { code: '187', description: '6098U', closeDate: '' },
        { code: '340', description: '610A', closeDate: '' },
        { code: '388', description: '6265B', closeDate: '' },
        { code: '201', description: '630', closeDate: '' },
        { code: '204', description: '6506R', closeDate: '' },
        { code: '349', description: '65085', closeDate: '' },
        { code: '184', description: '65093', closeDate: '' },
        { code: '253', description: '6637G', closeDate: '' },
        { code: '110', description: '674TC', closeDate: '' },
        { code: '409', description: '6775C', closeDate: '' },
        { code: '126', description: '678', closeDate: '' },
        { code: '430', description: '6790', closeDate: '' },
        { code: '1053', description: '6968A', closeDate: '' },
        { code: '1054', description: '6971A', closeDate: '' },
        { code: '1041', description: '6974A', closeDate: '' },
        { code: '1043', description: '6977A', closeDate: '' },
        { code: '1052', description: '6981A', closeDate: '' },
        { code: '1051', description: '6982A', closeDate: '' },
        { code: '1270', description: '6987A', closeDate: '' },
        { code: '945', description: '72472', closeDate: '' },
        { code: '356', description: '7247J', closeDate: '' },
        { code: '1563', description: '7255N', closeDate: '' },
        { code: '128', description: '72593', closeDate: '' },
        { code: '127', description: '72594', closeDate: '' },
        { code: '129', description: '72595', closeDate: '' },
        { code: '1729', description: '7272N', closeDate: '' },
        { code: '1903', description: '7274N', closeDate: '' },
        { code: '699', description: '7327', closeDate: '' },
        { code: '87', description: '748AM', closeDate: '' },
        { code: '76', description: '751AM', closeDate: '' },
        { code: '78', description: '752AM', closeDate: '' },
        { code: '79', description: '753AM', closeDate: '' },
        { code: '93', description: '754AM', closeDate: '' },
        { code: '80', description: '755AM', closeDate: '' },
        { code: '88', description: '759AM', closeDate: '' },
        { code: '421', description: '7681U', closeDate: '' },
        { code: '118', description: '775TC', closeDate: '' },
        { code: '780', description: '7777', closeDate: '' },
        { code: '442', description: '777HIHH8', closeDate: '' },
        { code: '434', description: '789', closeDate: '' },
        { code: '671', description: '789789789789786', closeDate: '' },
        { code: '73', description: '791AM', closeDate: '' },
        { code: '85', description: '796AM', closeDate: '' },
        { code: '155', description: '801MR', closeDate: '' },
        { code: '160', description: '802MR', closeDate: '' },
        { code: '159', description: '803MR', closeDate: '' },
        { code: '81', description: '805MR', closeDate: '' },
        { code: '124', description: '806MR', closeDate: '' },
        { code: '86', description: '807AM', closeDate: '' },
        { code: '125', description: '807MR', closeDate: '' },
        { code: '342', description: '814A', closeDate: '' },
        { code: '119', description: '839SA', closeDate: '' },
        { code: '337', description: '841BP', closeDate: '' },
        { code: '422', description: '843BP', closeDate: '' },
        { code: '22', description: '844BP', closeDate: '' },
        { code: '122', description: '846BP', closeDate: '' },
        { code: '423', description: '847BP', closeDate: '' },
        { code: '424', description: '848BP', closeDate: '' },
        { code: '120', description: '849BP', closeDate: '' },
        { code: '12', description: '853BP', closeDate: '' },
        { code: '355', description: '854BP', closeDate: '' },
        { code: '439', description: '8798789789', closeDate: '' },
        { code: '781', description: '88888', closeDate: '' },
        { code: '368', description: '890', closeDate: '' },
        { code: '428', description: '8900', closeDate: '' },
        { code: '446', description: '89076', closeDate: '' },
        { code: '215', description: '896WD', closeDate: '' },
        { code: '772', description: '898', closeDate: '' },
        { code: '265', description: '8998', closeDate: '' },
        { code: '431', description: '9075', closeDate: '' },
        { code: '777', description: '9089', closeDate: '' },
        { code: '784', description: '909090', closeDate: '' },
        { code: '212', description: '93285', closeDate: '' },
        { code: '350', description: '9403Y', closeDate: '' },
        { code: '20', description: '9769N', closeDate: '' },
        { code: '433', description: '9876', closeDate: '' },
        { code: '366', description: '988', closeDate: '' },
        { code: '782', description: '99999', closeDate: '' },
        { code: '774', description: 'AB C172 TEST', closeDate: '' },
        { code: '773', description: 'ABC1234', closeDate: '' },
        { code: '546', description: 'ABQ-1', closeDate: '' },
        { code: '769', description: 'AIR-C12', closeDate: '' },
        { code: '728', description: 'ALL-ASSET-1', closeDate: '' },
        { code: '101', description: 'AN-5', closeDate: '' },
        { code: '121', description: 'AN-6', closeDate: '' },
        { code: '352', description: 'AS350', closeDate: '' },
        { code: '723', description: 'ASTAR1', closeDate: '' },
        { code: '3176', description: 'ASTAR23', closeDate: '' },
        { code: '851', description: 'ATEST1', closeDate: '' },
        { code: '828', description: 'ANGULARTEST', closeDate: '' },
        { code: '719', description: 'BADYEARTEST', closeDate: '' },
        { code: '224', description: 'BMU ASSET', closeDate: '' },
        { code: '438', description: 'BR 549-4', closeDate: '' },
        { code: '435', description: 'BR-549-1', closeDate: '' },
        { code: '436', description: 'BR-549-2', closeDate: '' },
        { code: '437', description: 'BR549-3', closeDate: '' },
        { code: '225', description: 'BUF ASSET', closeDate: '' },
        { code: '813', description: 'CACHETESTBUF', closeDate: '' },
        { code: '724', description: 'CBP104', closeDate: '' },
        { code: '725', description: 'CBP108', closeDate: '' },
        { code: '379', description: 'CBP113', closeDate: '' },
        { code: '75', description: 'CBP119', closeDate: '' },
        { code: '82', description: 'CBP125', closeDate: '' },
        { code: '227', description: 'CCM ASSET', closeDate: '' },
        { code: '1009', description: 'CHICAGO AS350', closeDate: '' },
        { code: '228', description: 'CIW ASSET', closeDate: '' },
        { code: '1007', description: 'CRP TEST 1', closeDate: '' },
        { code: '1006', description: 'DANBTEST ASSET', closeDate: '' },
        { code: '720', description: 'DANSAVETEST', closeDate: '' },
        { code: '705', description: 'DANTEST', closeDate: '' },
        { code: '733', description: 'DANUASTEST', closeDate: '' },
        { code: '754', description: 'DANVTEST3', closeDate: '' },
        { code: '230', description: 'DAS ASSET', closeDate: '' },
        { code: '3205', description: 'DB -TEST11', closeDate: '' },
        { code: '3206', description: 'DB FLOAT TEST 1', closeDate: '' },
        { code: '3164', description: 'DB IP TEST SOLO', closeDate: '' },
        { code: '814', description: 'DB TEST ASSET MARINE FOR BUF', closeDate: '' },
        { code: '3162', description: 'DB TEST DB1', closeDate: '' },
        { code: '3178', description: 'DB-33TEST-COATAL', closeDate: '' },
        { code: '803', description: 'DB55555', closeDate: '' },
        { code: '231', description: 'DES ASSET', closeDate: '' },
        { code: '232', description: 'DMN ASSET', closeDate: '' },
        { code: '555', description: 'DMN-1', closeDate: '' },
        { code: '234', description: 'DRT ASSET', closeDate: '' },
        { code: '1', description: 'DRT TEST', closeDate: '' },
        { code: '235', description: 'DSM ASSET', closeDate: '' },
        { code: '236', description: 'DTW ASSET', closeDate: '' },
        { code: '570', description: 'DUMMY', closeDate: '' },
        { code: '547', description: 'DUMMY-547', closeDate: '' },
        { code: '548', description: 'DUMMY-548', closeDate: '' },
        { code: '549', description: 'DUMMY-549', closeDate: '' },
        { code: '550', description: 'DUMMY-550', closeDate: '' },
        { code: '551', description: 'DUMMY-551', closeDate: '' },
        { code: '552', description: 'DUMMY-552', closeDate: '' },
        { code: '553', description: 'DUMMY-553', closeDate: '' },
        { code: '554', description: 'DUMMY-554', closeDate: '' },
        { code: '556', description: 'DUMMY-556', closeDate: '' },
        { code: '557', description: 'DUMMY-557', closeDate: '' },
        { code: '558', description: 'DUMMY-558', closeDate: '' },
        { code: '559', description: 'DUMMY-559', closeDate: '' },
        { code: '560', description: 'DUMMY-560', closeDate: '' },
        { code: '561', description: 'DUMMY-561', closeDate: '' },
        { code: '562', description: 'DUMMY-562', closeDate: '' },
        { code: '563', description: 'DUMMY-563', closeDate: '' },
        { code: '859', description: 'DUMMY-566', closeDate: '' },
        { code: '567', description: 'DUMMY-567', closeDate: '' },
        { code: '862', description: 'DUMMY-567 1', closeDate: '' },
        { code: '863', description: 'DUMMY-567 2', closeDate: '' },
        { code: '568', description: 'DUMMY-568', closeDate: '' },
        { code: '569', description: 'DUMMY-569', closeDate: '' },
        { code: '571', description: 'DUMMY-571', closeDate: '' },
        { code: '868', description: 'DUMMY-571 \u003d', closeDate: '' },
        { code: '572', description: 'DUMMY-572', closeDate: '' },
        { code: '573', description: 'DUMMY-573', closeDate: '' },
        { code: '574', description: 'DUMMY-574', closeDate: '' },
        { code: '575', description: 'DUMMY-575', closeDate: '' },
        { code: '576', description: 'DUMMY-576', closeDate: '' },
        { code: '577', description: 'DUMMY-577', closeDate: '' },
        { code: '578', description: 'DUMMY-578', closeDate: '' },
        { code: '579', description: 'DUMMY-579', closeDate: '' },
        { code: '580', description: 'DUMMY-580', closeDate: '' },
        { code: '581', description: 'DUMMY-581', closeDate: '' },
        { code: '582', description: 'DUMMY-582', closeDate: '' },
        { code: '583', description: 'DUMMY-583', closeDate: '' },
        { code: '584', description: 'DUMMY-584', closeDate: '' },
        { code: '585', description: 'DUMMY-585', closeDate: '' },
        { code: '586', description: 'DUMMY-586', closeDate: '' },
        { code: '587', description: 'DUMMY-587', closeDate: '' },
        { code: '588', description: 'DUMMY-588', closeDate: '' },
        { code: '589', description: 'DUMMY-589', closeDate: '' },
        { code: '590', description: 'DUMMY-590', closeDate: '' },
        { code: '592', description: 'DUMMY-592', closeDate: '' },
        { code: '593', description: 'DUMMY-593', closeDate: '' },
        { code: '594', description: 'DUMMY-594', closeDate: '' },
        { code: '595', description: 'DUMMY-595', closeDate: '' },
        { code: '596', description: 'DUMMY-596', closeDate: '' },
        { code: '598', description: 'DUMMY-598', closeDate: '' },
        { code: '599', description: 'DUMMY-599', closeDate: '' },
        { code: '600', description: 'DUMMY-600', closeDate: '' },
        { code: '601', description: 'DUMMY-601', closeDate: '' },
        { code: '603', description: 'DUMMY-603', closeDate: '' },
        { code: '604', description: 'DUMMY-604', closeDate: '' },
        { code: '605', description: 'DUMMY-605', closeDate: '' },
        { code: '606', description: 'DUMMY-606', closeDate: '' },
        { code: '607', description: 'DUMMY-607', closeDate: '' },
        { code: '608', description: 'DUMMY-608', closeDate: '' },
        { code: '609', description: 'DUMMY-609', closeDate: '' },
        { code: '610', description: 'DUMMY-610', closeDate: '' },
        { code: '611', description: 'DUMMY-611', closeDate: '' },
        { code: '612', description: 'DUMMY-612', closeDate: '' },
        { code: '613', description: 'DUMMY-613', closeDate: '' },
        { code: '614', description: 'DUMMY-614', closeDate: '' },
        { code: '615', description: 'DUMMY-615', closeDate: '' },
        { code: '616', description: 'DUMMY-616', closeDate: '' },
        { code: '617', description: 'DUMMY-617', closeDate: '' },
        { code: '618', description: 'DUMMY-618', closeDate: '' },
        { code: '619', description: 'DUMMY-619', closeDate: '' },
        { code: '620', description: 'DUMMY-620', closeDate: '' },
        { code: '621', description: 'DUMMY-621', closeDate: '' },
        { code: '622', description: 'DUMMY-622', closeDate: '' },
        { code: '623', description: 'DUMMY-623', closeDate: '' },
        { code: '624', description: 'DUMMY-624', closeDate: '' },
        { code: '625', description: 'DUMMY-625', closeDate: '' },
        { code: '626', description: 'DUMMY-626', closeDate: '' },
        { code: '627', description: 'DUMMY-627', closeDate: '' },
        { code: '628', description: 'DUMMY-628', closeDate: '' },
        { code: '630', description: 'DUMMY-630', closeDate: '' },
        { code: '631', description: 'DUMMY-631', closeDate: '' },
        { code: '633', description: 'DUMMY-633', closeDate: '' },
        { code: '634', description: 'DUMMY-634', closeDate: '' },
        { code: '635', description: 'DUMMY-635', closeDate: '' },
        { code: '636', description: 'DUMMY-636', closeDate: '' },
        { code: '775', description: 'EALASSET', closeDate: '' },
        { code: '3175', description: 'EDTEST0022', closeDate: '' },
        { code: '237', description: 'ELC ASSET', closeDate: '' },
        { code: '238', description: 'ELP ASSET', closeDate: '' },
        { code: '239', description: 'EMU ASSET', closeDate: '' },
        { code: '729', description: 'EMU PARY\u0027S BIG BOAT', closeDate: '' },
        { code: '730', description: 'EMU- ROB\u0027S JOHN BOAT', closeDate: '' },
        { code: '737', description: 'ENGINEAFTERSAVE', closeDate: '' },
        { code: '240', description: 'EPT ASSET', closeDate: '' },
        { code: '867', description: 'F468TXS', closeDate: '' },
        { code: '3181', description: 'FDDFDF', closeDate: '' },
        { code: '241', description: 'FDO ASSET', closeDate: '' },
        { code: '242', description: 'FHU ASSET', closeDate: '' },
        { code: '243', description: 'FLL ASSET', closeDate: '' },
        { code: '244', description: 'FMY ASSET', closeDate: '' },
        { code: '856', description: 'FRESSS', closeDate: '' },
        { code: '245', description: 'FTP ASSET', closeDate: '' },
        { code: '3196', description: 'FTYU', closeDate: '' },
        { code: '246', description: 'GFK ASSET', closeDate: '' },
        { code: '247', description: 'GMO ASSET', closeDate: '' },
        { code: '702', description: 'GREG HDQ ASSETT', closeDate: '' },
        { code: '847', description: 'GREGASSET34', closeDate: '' },
        { code: '248', description: 'GTF ASSET', closeDate: '' },
        { code: '790', description: 'GTF NEW 1', closeDate: '' },
        { code: '3179', description: 'GTF NEW 2', closeDate: '' },
        { code: '864', description: 'GTF-11111-DDDD', closeDate: '' },
        { code: '865', description: 'GTF-1112-333', closeDate: '' },
        { code: '866', description: 'GTF-1113-DDDD', closeDate: '' },
        { code: '249', description: 'GUL ASSET', closeDate: '' },
        { code: '250', description: 'HDQ ASSET', closeDate: '' },
        { code: '811', description: 'HHH', closeDate: '' },
        { code: '3200', description: 'HHJJ', closeDate: '' },
        { code: '3203', description: 'HJKI', closeDate: '' },
        { code: '251', description: 'HMU ASSET', closeDate: '' },
        { code: '252', description: 'HOU ASSET', closeDate: '' },
        { code: '233', description: 'HQ ASSET', closeDate: '' },
        { code: '266', description: 'HQ-2 ASSET', closeDate: '' },
        { code: '591', description: 'HQ-3 ASSET', closeDate: '' },
        { code: '254', description: 'IAC ASSET', closeDate: '' },
        { code: '744', description: 'IMABOAT', closeDate: '' },
        { code: '3191', description: 'IOP', closeDate: '' },
        { code: '3187', description: 'IUY', closeDate: '' },
        { code: '255', description: 'JAC ASSET', closeDate: '' },
        { code: '1008', description: 'JAC DB TEST', closeDate: '' },
        { code: '256', description: 'JAX ASSET', closeDate: '' },
        { code: '44', description: 'JAX ASSET 2', closeDate: '' },
        { code: '257', description: 'JAX UAS', closeDate: '' },
        { code: '3199', description: 'JHGF', closeDate: '' },
        { code: '3189', description: 'JKI', closeDate: '' },
        { code: '258', description: 'KYL ASSET', closeDate: '' },
        { code: '259', description: 'KYW ASSET', closeDate: '' },
        { code: '722', description: 'LETSGOCAPS', closeDate: '' },
        { code: '3193', description: 'LKJH', closeDate: '' },
        { code: '3190', description: 'LKL', closeDate: '' },
        { code: '3192', description: 'LOIU', closeDate: '' },
        { code: '260', description: 'LRD ASSET', closeDate: '' },
        { code: '261', description: 'LSC ASSET', closeDate: '' },
        { code: '1559', description: 'M303323', closeDate: '' },
        { code: '2146', description: 'M303330', closeDate: '' },
        { code: '1888', description: 'M303351', closeDate: '' },
        { code: '1686', description: 'M392768', closeDate: '' },
        { code: '262', description: 'MAF ASSET', closeDate: '' },
        { code: '263', description: 'MAR ASSET', closeDate: '' },
        { code: '264', description: 'MAZ ASSET', closeDate: '' },
        { code: '267', description: 'MFE ASSET', closeDate: '' },
        { code: '268', description: 'MIA ASSET 1', closeDate: '' },
        { code: '1031', description: 'MILITARY BE20', closeDate: '' },
        { code: '1021', description: 'MILITARY P3', closeDate: '' },
        { code: '1030', description: 'MILITARY UH60', closeDate: '' },
        { code: '269', description: 'MMU ASSET', closeDate: '' },
        { code: '270', description: 'MRU ASSET', closeDate: '' },
        { code: '271', description: 'MSY ASSET', closeDate: '' },
        { code: '272', description: 'MTC ASSET', closeDate: '' },
        { code: '3180', description: 'MY TEST3', closeDate: '' },
        { code: '717', description: 'MYASSET', closeDate: '' },
        { code: '727', description: 'MYASSET1', closeDate: '' },
        { code: '870', description: 'MYFLEET', closeDate: '' },
        { code: '1004', description: 'MYTEST1', closeDate: '' },
        { code: '1003', description: 'MYTESTASSET', closeDate: '' },
        { code: '776', description: 'MYTESTEAL', closeDate: '' },
        { code: '1271', description: 'N108F', closeDate: '' },
        { code: '848', description: 'N123333333', closeDate: '' },
        { code: '800', description: 'N12345', closeDate: '' },
        { code: '844', description: 'N123456', closeDate: '' },
        { code: '200', description: 'N142CS', closeDate: '' },
        { code: '199', description: 'N143CS', closeDate: '' },
        { code: '14', description: 'N146CB', closeDate: '' },
        { code: '418', description: 'N146CS', closeDate: '' },
        { code: '1155', description: 'N161V', closeDate: '' },
        { code: '1898', description: 'N192F', closeDate: '' },
        { code: '2141', description: 'N218Q', closeDate: '' },
        { code: '1562', description: 'N2734K', closeDate: '' },
        { code: '734', description: 'N360INC', closeDate: '' },
        { code: '845', description: 'N4567', closeDate: '' },
        { code: '384', description: 'N505J', closeDate: '' },
        { code: '4', description: 'N505Q', closeDate: '' },
        { code: '208', description: 'N505U', closeDate: '' },
        { code: '175', description: 'N51216', closeDate: '' },
        { code: '801', description: 'N54322', closeDate: '' },
        { code: '1895', description: 'N631L', closeDate: '' },
        { code: '1035', description: 'N6506V', closeDate: '' },
        { code: '2151', description: 'N7252N', closeDate: '' },
        { code: '426', description: 'N741SK', closeDate: '' },
        { code: '393', description: 'N752CC', closeDate: '' },
        { code: '149', description: 'N769SK', closeDate: '' },
        { code: '1231', description: 'N785MC', closeDate: '' },
        { code: '1175', description: 'N842BP', closeDate: '' },
        { code: '842', description: 'N8999', closeDate: '' },
        { code: '1130', description: 'N917A', closeDate: '' },
        { code: '273', description: 'NBR ASSET', closeDate: '' },
        { code: '274', description: 'NCR ASSET', closeDate: '' },
        { code: '849', description: 'NEW ASSET 10', closeDate: '' },
        { code: '787', description: 'NEW ASSET GTF1', closeDate: '' },
        { code: '738', description: 'NEWADD029', closeDate: '' },
        { code: '732', description: 'NEWVESSELTEST', closeDate: '' },
        { code: '275', description: 'NFM ASSET', closeDate: '' },
        { code: '276', description: 'NLC ASSET', closeDate: '' },
        { code: '873', description: 'NRIVERINE12', closeDate: '' },
        { code: '278', description: 'NYC ASSET', closeDate: '' },
        { code: '3188', description: 'OIUY', closeDate: '' },
        { code: '279', description: 'OKC ASSET', closeDate: '' },
        { code: '3167', description: 'OKC TEST ASSE T222222', closeDate: '' },
        { code: '3166', description: 'OKC TEST ASSET', closeDate: '' },
        { code: '3182', description: 'OPIU', closeDate: '' },
        { code: '381', description: 'P012', closeDate: '' },
        { code: '382', description: 'P013', closeDate: '' },
        { code: '378', description: 'P31', closeDate: '' },
        { code: '380', description: 'P890', closeDate: '' },
        { code: '280', description: 'PAM ASSET', closeDate: '' },
        { code: '281', description: 'PBG ASSET', closeDate: '' },
        { code: '282', description: 'PCM ASSET', closeDate: '' },
        { code: '283', description: 'PHM ASSET', closeDate: '' },
        { code: '284', description: 'PIM ASSET', closeDate: '' },
        { code: '718', description: 'POP UP?', closeDate: '' },
        { code: '809', description: 'PRESELENIUM', closeDate: '' },
        { code: '285', description: 'PSE ASSET', closeDate: '' },
        { code: '286', description: 'PSL ASSET', closeDate: '' },
        { code: '287', description: 'PTR ASSET', closeDate: '' },
        { code: '288', description: 'RDR ASSET', closeDate: '' },
        { code: '872', description: 'RIVERINE ASSET111', closeDate: '' },
        { code: '871', description: 'RIVERINE12', closeDate: '' },
        { code: '289', description: 'RMU ASSET', closeDate: '' },
        { code: '457', description: 'ROBASSET', closeDate: '' },
        { code: '749', description: 'ROBMIDNIGHTASSET', closeDate: '' },
        { code: '767', description: 'ROBTEST47', closeDate: '' },
        { code: '761', description: 'ROBTESTJFDKSLAJFLD', closeDate: '' },
        { code: '751', description: 'ROBVESSELTEST2', closeDate: '' },
        { code: '822', description: 'RELOCATIONTEST2', closeDate: '' },
        { code: '290', description: 'SAC ASSET', closeDate: '' },
        { code: '291', description: 'SAD ASSET', closeDate: '' },
        { code: '292', description: 'SAN ASSET', closeDate: '' },
        { code: '293', description: 'SAT ASSET', closeDate: '' },
        { code: '294', description: 'SDM ASSET', closeDate: '' },
        { code: '295', description: 'SER ASSET', closeDate: '' },
        { code: '296', description: 'SFF ASSET', closeDate: '' },
        { code: '1012', description: 'SIMULATOR B350', closeDate: '' },
        { code: '1013', description: 'SIMULATOR BE20', closeDate: '' },
        { code: '1016', description: 'SIMULATOR C550', closeDate: '' },
        { code: '1018', description: 'SIMULATOR DH8', closeDate: '' },
        { code: '1110', description: 'SIMULATOR GCS', closeDate: '' },
        { code: '1029', description: 'SIMULATOR UH60', closeDate: '' },
        { code: '297', description: 'SJT ASSET', closeDate: '' },
        { code: '299', description: 'SMU ASSET', closeDate: '' },
        { code: '308', description: 'SSASD', closeDate: '' },
        { code: '300', description: 'STT ASSET', closeDate: '' },
        { code: '301', description: 'SWR ASSET', closeDate: '' },
        { code: '855', description: 'TAIL', closeDate: '' },
        { code: '830', description: 'TAIL 11CVAV', closeDate: '' },
        { code: '850', description: 'TAIL 23', closeDate: '' },
        { code: '823', description: 'TAIL 6', closeDate: '' },
        { code: '852', description: 'TAIL JK', closeDate: '' },
        { code: '302', description: 'TAM ASSET', closeDate: '' },
        { code: '3161', description: 'TB', closeDate: '' },
        { code: '2027', description: 'TBD', closeDate: '' },
        { code: '2026', description: 'TBD', closeDate: '' },
        { code: '1994', description: 'TBD', closeDate: '' },
        { code: '1993', description: 'TBD', closeDate: '' },
        { code: '1992', description: 'TBD', closeDate: '' },
        { code: '1991', description: 'TBD', closeDate: '' },
        { code: '2025', description: 'TBD', closeDate: '' },
        { code: '2024', description: 'TBD', closeDate: '' },
        { code: '2023', description: 'TBD', closeDate: '' },
        { code: '2022', description: 'TBD', closeDate: '' },
        { code: '2021', description: 'TBD', closeDate: '' },
        { code: '2020', description: 'TBD', closeDate: '' },
        { code: '2019', description: 'TBD', closeDate: '' },
        { code: '2018', description: 'TBD', closeDate: '' },
        { code: '2017', description: 'TBD', closeDate: '' },
        { code: '2016', description: 'TBD', closeDate: '' },
        { code: '2015', description: 'TBD', closeDate: '' },
        { code: '2014', description: 'TBD', closeDate: '' },
        { code: '2013', description: 'TBD', closeDate: '' },
        { code: '2012', description: 'TBD', closeDate: '' },
        { code: '2011', description: 'TBD', closeDate: '' },
        { code: '2010', description: 'TBD', closeDate: '' },
        { code: '2009', description: 'TBD', closeDate: '' },
        { code: '2008', description: 'TBD', closeDate: '' },
        { code: '2007', description: 'TBD', closeDate: '' },
        { code: '2006', description: 'TBD', closeDate: '' },
        { code: '2005', description: 'TBD', closeDate: '' },
        { code: '2004', description: 'TBD', closeDate: '' },
        { code: '2003', description: 'TBD', closeDate: '' },
        { code: '2002', description: 'TBD', closeDate: '' },
        { code: '2001', description: 'TBD', closeDate: '' },
        { code: '2000', description: 'TBD', closeDate: '' },
        { code: '1999', description: 'TBD', closeDate: '' },
        { code: '1998', description: 'TBD', closeDate: '' },
        { code: '1997', description: 'TBD', closeDate: '' },
        { code: '1996', description: 'TBD', closeDate: '' },
        { code: '1995', description: 'TBD', closeDate: '' },
        { code: '2095', description: 'TBD', closeDate: '' },
        { code: '2094', description: 'TBD', closeDate: '' },
        { code: '2093', description: 'TBD', closeDate: '' },
        { code: '2092', description: 'TBD', closeDate: '' },
        { code: '2091', description: 'TBD', closeDate: '' },
        { code: '2090', description: 'TBD', closeDate: '' },
        { code: '2089', description: 'TBD', closeDate: '' },
        { code: '2088', description: 'TBD', closeDate: '' },
        { code: '2087', description: 'TBD', closeDate: '' },
        { code: '2086', description: 'TBD', closeDate: '' },
        { code: '2085', description: 'TBD', closeDate: '' },
        { code: '2084', description: 'TBD', closeDate: '' },
        { code: '2083', description: 'TBD', closeDate: '' },
        { code: '2082', description: 'TBD', closeDate: '' },
        { code: '2081', description: 'TBD', closeDate: '' },
        { code: '2080', description: 'TBD', closeDate: '' },
        { code: '2079', description: 'TBD', closeDate: '' },
        { code: '2078', description: 'TBD', closeDate: '' },
        { code: '2077', description: 'TBD', closeDate: '' },
        { code: '2076', description: 'TBD', closeDate: '' },
        { code: '2075', description: 'TBD', closeDate: '' },
        { code: '2074', description: 'TBD', closeDate: '' },
        { code: '2073', description: 'TBD', closeDate: '' },
        { code: '2072', description: 'TBD', closeDate: '' },
        { code: '2071', description: 'TBD', closeDate: '' },
        { code: '2070', description: 'TBD', closeDate: '' },
        { code: '2069', description: 'TBD', closeDate: '' },
        { code: '2068', description: 'TBD', closeDate: '' },
        { code: '2066', description: 'TBD', closeDate: '' },
        { code: '2065', description: 'TBD', closeDate: '' },
        { code: '2064', description: 'TBD', closeDate: '' },
        { code: '2063', description: 'TBD', closeDate: '' },
        { code: '2062', description: 'TBD', closeDate: '' },
        { code: '2061', description: 'TBD', closeDate: '' },
        { code: '2060', description: 'TBD', closeDate: '' },
        { code: '2059', description: 'TBD', closeDate: '' },
        { code: '2058', description: 'TBD', closeDate: '' },
        { code: '2057', description: 'TBD', closeDate: '' },
        { code: '2056', description: 'TBD', closeDate: '' },
        { code: '2055', description: 'TBD', closeDate: '' },
        { code: '2054', description: 'TBD', closeDate: '' },
        { code: '2053', description: 'TBD', closeDate: '' },
        { code: '2052', description: 'TBD', closeDate: '' },
        { code: '2051', description: 'TBD', closeDate: '' },
        { code: '2050', description: 'TBD', closeDate: '' },
        { code: '2048', description: 'TBD', closeDate: '' },
        { code: '2047', description: 'TBD', closeDate: '' },
        { code: '2046', description: 'TBD', closeDate: '' },
        { code: '2045', description: 'TBD', closeDate: '' },
        { code: '2044', description: 'TBD', closeDate: '' },
        { code: '2043', description: 'TBD', closeDate: '' },
        { code: '2042', description: 'TBD', closeDate: '' },
        { code: '2041', description: 'TBD', closeDate: '' },
        { code: '2040', description: 'TBD', closeDate: '' },
        { code: '2038', description: 'TBD', closeDate: '' },
        { code: '2037', description: 'TBD', closeDate: '' },
        { code: '2036', description: 'TBD', closeDate: '' },
        { code: '2034', description: 'TBD', closeDate: '' },
        { code: '2033', description: 'TBD', closeDate: '' },
        { code: '2032', description: 'TBD', closeDate: '' },
        { code: '2031', description: 'TBD', closeDate: '' },
        { code: '2030', description: 'TBD', closeDate: '' },
        { code: '2029', description: 'TBD', closeDate: '' },
        { code: '2028', description: 'TBD', closeDate: '' },
        { code: '3139', description: 'TBD', closeDate: '' },
        { code: '3140', description: 'TBD', closeDate: '' },
        { code: '3141', description: 'TBD', closeDate: '' },
        { code: '3142', description: 'TBD', closeDate: '' },
        { code: '3143', description: 'TBD', closeDate: '' },
        { code: '3144', description: 'TBD', closeDate: '' },
        { code: '3145', description: 'TBD', closeDate: '' },
        { code: '3146', description: 'TBD', closeDate: '' },
        { code: '3147', description: 'TBD', closeDate: '' },
        { code: '3148', description: 'TBD', closeDate: '' },
        { code: '3149', description: 'TBD', closeDate: '' },
        { code: '3150', description: 'TBD', closeDate: '' },
        { code: '3151', description: 'TBD', closeDate: '' },
        { code: '3152', description: 'TBD', closeDate: '' },
        { code: '3153', description: 'TBD', closeDate: '' },
        { code: '3154', description: 'TBD', closeDate: '' },
        { code: '3155', description: 'TBD', closeDate: '' },
        { code: '3156', description: 'TBD', closeDate: '' },
        { code: '3157', description: 'TBD', closeDate: '' },
        { code: '3158', description: 'TBD', closeDate: '' },
        { code: '3159', description: 'TBD', closeDate: '' },
        { code: '3160', description: 'TBD', closeDate: '' },
        { code: '3165', description: 'TBD', closeDate: '' },
        { code: '2138', description: 'TBD', closeDate: '' },
        { code: '2137', description: 'TBD', closeDate: '' },
        { code: '2136', description: 'TBD', closeDate: '' },
        { code: '2135', description: 'TBD', closeDate: '' },
        { code: '2133', description: 'TBD', closeDate: '' },
        { code: '2132', description: 'TBD', closeDate: '' },
        { code: '2131', description: 'TBD', closeDate: '' },
        { code: '2130', description: 'TBD', closeDate: '' },
        { code: '2129', description: 'TBD', closeDate: '' },
        { code: '2128', description: 'TBD', closeDate: '' },
        { code: '2127', description: 'TBD', closeDate: '' },
        { code: '2126', description: 'TBD', closeDate: '' },
        { code: '2125', description: 'TBD', closeDate: '' },
        { code: '2124', description: 'TBD', closeDate: '' },
        { code: '2123', description: 'TBD', closeDate: '' },
        { code: '2122', description: 'TBD', closeDate: '' },
        { code: '2121', description: 'TBD', closeDate: '' },
        { code: '2120', description: 'TBD', closeDate: '' },
        { code: '2119', description: 'TBD', closeDate: '' },
        { code: '2118', description: 'TBD', closeDate: '' },
        { code: '2117', description: 'TBD', closeDate: '' },
        { code: '2115', description: 'TBD', closeDate: '' },
        { code: '2114', description: 'TBD', closeDate: '' },
        { code: '2113', description: 'TBD', closeDate: '' },
        { code: '2112', description: 'TBD', closeDate: '' },
        { code: '2111', description: 'TBD', closeDate: '' },
        { code: '2110', description: 'TBD', closeDate: '' },
        { code: '2109', description: 'TBD', closeDate: '' },
        { code: '2108', description: 'TBD', closeDate: '' },
        { code: '2107', description: 'TBD', closeDate: '' },
        { code: '2106', description: 'TBD', closeDate: '' },
        { code: '2105', description: 'TBD', closeDate: '' },
        { code: '2104', description: 'TBD', closeDate: '' },
        { code: '2103', description: 'TBD', closeDate: '' },
        { code: '2102', description: 'TBD', closeDate: '' },
        { code: '2101', description: 'TBD', closeDate: '' },
        { code: '2100', description: 'TBD', closeDate: '' },
        { code: '2099', description: 'TBD', closeDate: '' },
        { code: '2098', description: 'TBD', closeDate: '' },
        { code: '2097', description: 'TBD', closeDate: '' },
        { code: '2096', description: 'TBD', closeDate: '' },
        { code: '3075', description: 'TBD', closeDate: '' },
        { code: '3076', description: 'TBD', closeDate: '' },
        { code: '3077', description: 'TBD', closeDate: '' },
        { code: '3078', description: 'TBD', closeDate: '' },
        { code: '3079', description: 'TBD', closeDate: '' },
        { code: '3080', description: 'TBD', closeDate: '' },
        { code: '3081', description: 'TBD', closeDate: '' },
        { code: '3082', description: 'TBD', closeDate: '' },
        { code: '3083', description: 'TBD', closeDate: '' },
        { code: '3084', description: 'TBD', closeDate: '' },
        { code: '3085', description: 'TBD', closeDate: '' },
        { code: '3086', description: 'TBD', closeDate: '' },
        { code: '3087', description: 'TBD', closeDate: '' },
        { code: '3088', description: 'TBD', closeDate: '' },
        { code: '3089', description: 'TBD', closeDate: '' },
        { code: '3090', description: 'TBD', closeDate: '' },
        { code: '3091', description: 'TBD', closeDate: '' },
        { code: '3092', description: 'TBD', closeDate: '' },
        { code: '3093', description: 'TBD', closeDate: '' },
        { code: '3094', description: 'TBD', closeDate: '' },
        { code: '3095', description: 'TBD', closeDate: '' },
        { code: '3096', description: 'TBD', closeDate: '' },
        { code: '3097', description: 'TBD', closeDate: '' },
        { code: '3098', description: 'TBD', closeDate: '' },
        { code: '3099', description: 'TBD', closeDate: '' },
        { code: '3100', description: 'TBD', closeDate: '' },
        { code: '3101', description: 'TBD', closeDate: '' },
        { code: '3102', description: 'TBD', closeDate: '' },
        { code: '3103', description: 'TBD', closeDate: '' },
        { code: '3104', description: 'TBD', closeDate: '' },
        { code: '3105', description: 'TBD', closeDate: '' },
        { code: '3106', description: 'TBD', closeDate: '' },
        { code: '3107', description: 'TBD', closeDate: '' },
        { code: '3108', description: 'TBD', closeDate: '' },
        { code: '3109', description: 'TBD', closeDate: '' },
        { code: '3110', description: 'TBD', closeDate: '' },
        { code: '3111', description: 'TBD', closeDate: '' },
        { code: '3112', description: 'TBD', closeDate: '' },
        { code: '3113', description: 'TBD', closeDate: '' },
        { code: '3114', description: 'TBD', closeDate: '' },
        { code: '3115', description: 'TBD', closeDate: '' },
        { code: '3116', description: 'TBD', closeDate: '' },
        { code: '3117', description: 'TBD', closeDate: '' },
        { code: '3118', description: 'TBD', closeDate: '' },
        { code: '3119', description: 'TBD', closeDate: '' },
        { code: '3120', description: 'TBD', closeDate: '' },
        { code: '3121', description: 'TBD', closeDate: '' },
        { code: '3122', description: 'TBD', closeDate: '' },
        { code: '3123', description: 'TBD', closeDate: '' },
        { code: '3124', description: 'TBD', closeDate: '' },
        { code: '3125', description: 'TBD', closeDate: '' },
        { code: '3126', description: 'TBD', closeDate: '' },
        { code: '3127', description: 'TBD', closeDate: '' },
        { code: '3128', description: 'TBD', closeDate: '' },
        { code: '3129', description: 'TBD', closeDate: '' },
        { code: '3130', description: 'TBD', closeDate: '' },
        { code: '3131', description: 'TBD', closeDate: '' },
        { code: '3132', description: 'TBD', closeDate: '' },
        { code: '3133', description: 'TBD', closeDate: '' },
        { code: '3134', description: 'TBD', closeDate: '' },
        { code: '3135', description: 'TBD', closeDate: '' },
        { code: '3136', description: 'TBD', closeDate: '' },
        { code: '3137', description: 'TBD', closeDate: '' },
        { code: '3138', description: 'TBD', closeDate: '' },
        { code: '3011', description: 'TBD', closeDate: '' },
        { code: '3012', description: 'TBD', closeDate: '' },
        { code: '3013', description: 'TBD', closeDate: '' },
        { code: '3014', description: 'TBD', closeDate: '' },
        { code: '3015', description: 'TBD', closeDate: '' },
        { code: '3016', description: 'TBD', closeDate: '' },
        { code: '3017', description: 'TBD', closeDate: '' },
        { code: '3018', description: 'TBD', closeDate: '' },
        { code: '3019', description: 'TBD', closeDate: '' },
        { code: '3020', description: 'TBD', closeDate: '' },
        { code: '3021', description: 'TBD', closeDate: '' },
        { code: '3022', description: 'TBD', closeDate: '' },
        { code: '3023', description: 'TBD', closeDate: '' },
        { code: '3024', description: 'TBD', closeDate: '' },
        { code: '3025', description: 'TBD', closeDate: '' },
        { code: '3026', description: 'TBD', closeDate: '' },
        { code: '3027', description: 'TBD', closeDate: '' },
        { code: '3028', description: 'TBD', closeDate: '' },
        { code: '3029', description: 'TBD', closeDate: '' },
        { code: '3030', description: 'TBD', closeDate: '' },
        { code: '3031', description: 'TBD', closeDate: '' },
        { code: '3032', description: 'TBD', closeDate: '' },
        { code: '3033', description: 'TBD', closeDate: '' },
        { code: '3034', description: 'TBD', closeDate: '' },
        { code: '3035', description: 'TBD', closeDate: '' },
        { code: '3036', description: 'TBD', closeDate: '' },
        { code: '3037', description: 'TBD', closeDate: '' },
        { code: '3038', description: 'TBD', closeDate: '' },
        { code: '3039', description: 'TBD', closeDate: '' },
        { code: '3040', description: 'TBD', closeDate: '' },
        { code: '3041', description: 'TBD', closeDate: '' },
        { code: '3042', description: 'TBD', closeDate: '' },
        { code: '3043', description: 'TBD', closeDate: '' },
        { code: '3044', description: 'TBD', closeDate: '' },
        { code: '3045', description: 'TBD', closeDate: '' },
        { code: '3046', description: 'TBD', closeDate: '' },
        { code: '3047', description: 'TBD', closeDate: '' },
        { code: '3048', description: 'TBD', closeDate: '' },
        { code: '3049', description: 'TBD', closeDate: '' },
        { code: '3050', description: 'TBD', closeDate: '' },
        { code: '3051', description: 'TBD', closeDate: '' },
        { code: '3052', description: 'TBD', closeDate: '' },
        { code: '3053', description: 'TBD', closeDate: '' },
        { code: '3054', description: 'TBD', closeDate: '' },
        { code: '3055', description: 'TBD', closeDate: '' },
        { code: '3056', description: 'TBD', closeDate: '' },
        { code: '3057', description: 'TBD', closeDate: '' },
        { code: '3058', description: 'TBD', closeDate: '' },
        { code: '3059', description: 'TBD', closeDate: '' },
        { code: '3060', description: 'TBD', closeDate: '' },
        { code: '3061', description: 'TBD', closeDate: '' },
        { code: '3062', description: 'TBD', closeDate: '' },
        { code: '3063', description: 'TBD', closeDate: '' },
        { code: '3064', description: 'TBD', closeDate: '' },
        { code: '3065', description: 'TBD', closeDate: '' },
        { code: '3066', description: 'TBD', closeDate: '' },
        { code: '3067', description: 'TBD', closeDate: '' },
        { code: '3068', description: 'TBD', closeDate: '' },
        { code: '3069', description: 'TBD', closeDate: '' },
        { code: '3070', description: 'TBD', closeDate: '' },
        { code: '3071', description: 'TBD', closeDate: '' },
        { code: '3072', description: 'TBD', closeDate: '' },
        { code: '3073', description: 'TBD', closeDate: '' },
        { code: '3074', description: 'TBD', closeDate: '' },
        { code: '2947', description: 'TBD', closeDate: '' },
        { code: '2948', description: 'TBD', closeDate: '' },
        { code: '2949', description: 'TBD', closeDate: '' },
        { code: '2950', description: 'TBD', closeDate: '' },
        { code: '2951', description: 'TBD', closeDate: '' },
        { code: '2952', description: 'TBD', closeDate: '' },
        { code: '2953', description: 'TBD', closeDate: '' },
        { code: '2954', description: 'TBD', closeDate: '' },
        { code: '2955', description: 'TBD', closeDate: '' },
        { code: '2956', description: 'TBD', closeDate: '' },
        { code: '2957', description: 'TBD', closeDate: '' },
        { code: '2958', description: 'TBD', closeDate: '' },
        { code: '2959', description: 'TBD', closeDate: '' },
        { code: '2960', description: 'TBD', closeDate: '' },
        { code: '2961', description: 'TBD', closeDate: '' },
        { code: '2962', description: 'TBD', closeDate: '' },
        { code: '2963', description: 'TBD', closeDate: '' },
        { code: '2964', description: 'TBD', closeDate: '' },
        { code: '2965', description: 'TBD', closeDate: '' },
        { code: '2966', description: 'TBD', closeDate: '' },
        { code: '2967', description: 'TBD', closeDate: '' },
        { code: '2968', description: 'TBD', closeDate: '' },
        { code: '2969', description: 'TBD', closeDate: '' },
        { code: '2970', description: 'TBD', closeDate: '' },
        { code: '2971', description: 'TBD', closeDate: '' },
        { code: '2972', description: 'TBD', closeDate: '' },
        { code: '2973', description: 'TBD', closeDate: '' },
        { code: '2974', description: 'TBD', closeDate: '' },
        { code: '2975', description: 'TBD', closeDate: '' },
        { code: '2976', description: 'TBD', closeDate: '' },
        { code: '2977', description: 'TBD', closeDate: '' },
        { code: '2978', description: 'TBD', closeDate: '' },
        { code: '2979', description: 'TBD', closeDate: '' },
        { code: '2980', description: 'TBD', closeDate: '' },
        { code: '2981', description: 'TBD', closeDate: '' },
        { code: '2982', description: 'TBD', closeDate: '' },
        { code: '2983', description: 'TBD', closeDate: '' },
        { code: '2984', description: 'TBD', closeDate: '' },
        { code: '2985', description: 'TBD', closeDate: '' },
        { code: '2986', description: 'TBD', closeDate: '' },
        { code: '2987', description: 'TBD', closeDate: '' },
        { code: '2988', description: 'TBD', closeDate: '' },
        { code: '2989', description: 'TBD', closeDate: '' },
        { code: '2990', description: 'TBD', closeDate: '' },
        { code: '2991', description: 'TBD', closeDate: '' },
        { code: '2992', description: 'TBD', closeDate: '' },
        { code: '2993', description: 'TBD', closeDate: '' },
        { code: '2994', description: 'TBD', closeDate: '' },
        { code: '2995', description: 'TBD', closeDate: '' },
        { code: '2996', description: 'TBD', closeDate: '' },
        { code: '2997', description: 'TBD', closeDate: '' },
        { code: '2998', description: 'TBD', closeDate: '' },
        { code: '2999', description: 'TBD', closeDate: '' },
        { code: '3000', description: 'TBD', closeDate: '' },
        { code: '3001', description: 'TBD', closeDate: '' },
        { code: '3002', description: 'TBD', closeDate: '' },
        { code: '3003', description: 'TBD', closeDate: '' },
        { code: '3004', description: 'TBD', closeDate: '' },
        { code: '3005', description: 'TBD', closeDate: '' },
        { code: '3006', description: 'TBD', closeDate: '' },
        { code: '3007', description: 'TBD', closeDate: '' },
        { code: '3008', description: 'TBD', closeDate: '' },
        { code: '3009', description: 'TBD', closeDate: '' },
        { code: '3010', description: 'TBD', closeDate: '' },
        { code: '2883', description: 'TBD', closeDate: '' },
        { code: '2884', description: 'TBD', closeDate: '' },
        { code: '2885', description: 'TBD', closeDate: '' },
        { code: '2886', description: 'TBD', closeDate: '' },
        { code: '2887', description: 'TBD', closeDate: '' },
        { code: '2888', description: 'TBD', closeDate: '' },
        { code: '2889', description: 'TBD', closeDate: '' },
        { code: '2890', description: 'TBD', closeDate: '' },
        { code: '2891', description: 'TBD', closeDate: '' },
        { code: '2892', description: 'TBD', closeDate: '' },
        { code: '2893', description: 'TBD', closeDate: '' },
        { code: '2894', description: 'TBD', closeDate: '' },
        { code: '2895', description: 'TBD', closeDate: '' },
        { code: '2896', description: 'TBD', closeDate: '' },
        { code: '2897', description: 'TBD', closeDate: '' },
        { code: '2898', description: 'TBD', closeDate: '' },
        { code: '2899', description: 'TBD', closeDate: '' },
        { code: '2900', description: 'TBD', closeDate: '' },
        { code: '2901', description: 'TBD', closeDate: '' },
        { code: '2902', description: 'TBD', closeDate: '' },
        { code: '2903', description: 'TBD', closeDate: '' },
        { code: '2904', description: 'TBD', closeDate: '' },
        { code: '2905', description: 'TBD', closeDate: '' },
        { code: '2906', description: 'TBD', closeDate: '' },
        { code: '2907', description: 'TBD', closeDate: '' },
        { code: '2908', description: 'TBD', closeDate: '' },
        { code: '2909', description: 'TBD', closeDate: '' },
        { code: '2910', description: 'TBD', closeDate: '' },
        { code: '2911', description: 'TBD', closeDate: '' },
        { code: '2912', description: 'TBD', closeDate: '' },
        { code: '2913', description: 'TBD', closeDate: '' },
        { code: '2914', description: 'TBD', closeDate: '' },
        { code: '2915', description: 'TBD', closeDate: '' },
        { code: '2916', description: 'TBD', closeDate: '' },
        { code: '2917', description: 'TBD', closeDate: '' },
        { code: '2918', description: 'TBD', closeDate: '' },
        { code: '2919', description: 'TBD', closeDate: '' },
        { code: '2920', description: 'TBD', closeDate: '' },
        { code: '2921', description: 'TBD', closeDate: '' },
        { code: '2922', description: 'TBD', closeDate: '' },
        { code: '2923', description: 'TBD', closeDate: '' },
        { code: '2924', description: 'TBD', closeDate: '' },
        { code: '2925', description: 'TBD', closeDate: '' },
        { code: '2926', description: 'TBD', closeDate: '' },
        { code: '2927', description: 'TBD', closeDate: '' },
        { code: '2928', description: 'TBD', closeDate: '' },
        { code: '2929', description: 'TBD', closeDate: '' },
        { code: '2930', description: 'TBD', closeDate: '' },
        { code: '2931', description: 'TBD', closeDate: '' },
        { code: '2932', description: 'TBD', closeDate: '' },
        { code: '2933', description: 'TBD', closeDate: '' },
        { code: '2934', description: 'TBD', closeDate: '' },
        { code: '2935', description: 'TBD', closeDate: '' },
        { code: '2936', description: 'TBD', closeDate: '' },
        { code: '2937', description: 'TBD', closeDate: '' },
        { code: '2938', description: 'TBD', closeDate: '' },
        { code: '2939', description: 'TBD', closeDate: '' },
        { code: '2940', description: 'TBD', closeDate: '' },
        { code: '2941', description: 'TBD', closeDate: '' },
        { code: '2942', description: 'TBD', closeDate: '' },
        { code: '2943', description: 'TBD', closeDate: '' },
        { code: '2944', description: 'TBD', closeDate: '' },
        { code: '2945', description: 'TBD', closeDate: '' },
        { code: '2946', description: 'TBD', closeDate: '' },
        { code: '2820', description: 'TBD', closeDate: '' },
        { code: '2821', description: 'TBD', closeDate: '' },
        { code: '2822', description: 'TBD', closeDate: '' },
        { code: '2823', description: 'TBD', closeDate: '' },
        { code: '2824', description: 'TBD', closeDate: '' },
        { code: '2825', description: 'TBD', closeDate: '' },
        { code: '2826', description: 'TBD', closeDate: '' },
        { code: '2827', description: 'TBD', closeDate: '' },
        { code: '2828', description: 'TBD', closeDate: '' },
        { code: '2829', description: 'TBD', closeDate: '' },
        { code: '2830', description: 'TBD', closeDate: '' },
        { code: '2831', description: 'TBD', closeDate: '' },
        { code: '2832', description: 'TBD', closeDate: '' },
        { code: '2833', description: 'TBD', closeDate: '' },
        { code: '2834', description: 'TBD', closeDate: '' },
        { code: '2835', description: 'TBD', closeDate: '' },
        { code: '2836', description: 'TBD', closeDate: '' },
        { code: '2837', description: 'TBD', closeDate: '' },
        { code: '2838', description: 'TBD', closeDate: '' },
        { code: '2839', description: 'TBD', closeDate: '' },
        { code: '2840', description: 'TBD', closeDate: '' },
        { code: '2841', description: 'TBD', closeDate: '' },
        { code: '2842', description: 'TBD', closeDate: '' },
        { code: '2843', description: 'TBD', closeDate: '' },
        { code: '2844', description: 'TBD', closeDate: '' },
        { code: '2845', description: 'TBD', closeDate: '' },
        { code: '2846', description: 'TBD', closeDate: '' },
        { code: '2847', description: 'TBD', closeDate: '' },
        { code: '2848', description: 'TBD', closeDate: '' },
        { code: '2849', description: 'TBD', closeDate: '' },
        { code: '2850', description: 'TBD', closeDate: '' },
        { code: '2851', description: 'TBD', closeDate: '' },
        { code: '2852', description: 'TBD', closeDate: '' },
        { code: '2853', description: 'TBD', closeDate: '' },
        { code: '2854', description: 'TBD', closeDate: '' },
        { code: '2855', description: 'TBD', closeDate: '' },
        { code: '2856', description: 'TBD', closeDate: '' },
        { code: '2857', description: 'TBD', closeDate: '' },
        { code: '2858', description: 'TBD', closeDate: '' },
        { code: '2859', description: 'TBD', closeDate: '' },
        { code: '2860', description: 'TBD', closeDate: '' },
        { code: '2861', description: 'TBD', closeDate: '' },
        { code: '2862', description: 'TBD', closeDate: '' },
        { code: '2863', description: 'TBD', closeDate: '' },
        { code: '2864', description: 'TBD', closeDate: '' },
        { code: '2865', description: 'TBD', closeDate: '' },
        { code: '2866', description: 'TBD', closeDate: '' },
        { code: '2867', description: 'TBD', closeDate: '' },
        { code: '2868', description: 'TBD', closeDate: '' },
        { code: '2869', description: 'TBD', closeDate: '' },
        { code: '2870', description: 'TBD', closeDate: '' },
        { code: '2871', description: 'TBD', closeDate: '' },
        { code: '2872', description: 'TBD', closeDate: '' },
        { code: '2873', description: 'TBD', closeDate: '' },
        { code: '2874', description: 'TBD', closeDate: '' },
        { code: '2875', description: 'TBD', closeDate: '' },
        { code: '2876', description: 'TBD', closeDate: '' },
        { code: '2877', description: 'TBD', closeDate: '' },
        { code: '2878', description: 'TBD', closeDate: '' },
        { code: '2879', description: 'TBD', closeDate: '' },
        { code: '2880', description: 'TBD', closeDate: '' },
        { code: '2881', description: 'TBD', closeDate: '' },
        { code: '2882', description: 'TBD', closeDate: '' },
        { code: '2774', description: 'TBD', closeDate: '' },
        { code: '2775', description: 'TBD', closeDate: '' },
        { code: '2776', description: 'TBD', closeDate: '' },
        { code: '2777', description: 'TBD', closeDate: '' },
        { code: '2778', description: 'TBD', closeDate: '' },
        { code: '2779', description: 'TBD', closeDate: '' },
        { code: '2780', description: 'TBD', closeDate: '' },
        { code: '2781', description: 'TBD', closeDate: '' },
        { code: '2782', description: 'TBD', closeDate: '' },
        { code: '2783', description: 'TBD', closeDate: '' },
        { code: '2784', description: 'TBD', closeDate: '' },
        { code: '2785', description: 'TBD', closeDate: '' },
        { code: '2786', description: 'TBD', closeDate: '' },
        { code: '2787', description: 'TBD', closeDate: '' },
        { code: '2788', description: 'TBD', closeDate: '' },
        { code: '2789', description: 'TBD', closeDate: '' },
        { code: '2790', description: 'TBD', closeDate: '' },
        { code: '2791', description: 'TBD', closeDate: '' },
        { code: '2792', description: 'TBD', closeDate: '' },
        { code: '2793', description: 'TBD', closeDate: '' },
        { code: '2794', description: 'TBD', closeDate: '' },
        { code: '2795', description: 'TBD', closeDate: '' },
        { code: '2796', description: 'TBD', closeDate: '' },
        { code: '2797', description: 'TBD', closeDate: '' },
        { code: '2798', description: 'TBD', closeDate: '' },
        { code: '2799', description: 'TBD', closeDate: '' },
        { code: '2800', description: 'TBD', closeDate: '' },
        { code: '2801', description: 'TBD', closeDate: '' },
        { code: '2802', description: 'TBD', closeDate: '' },
        { code: '2803', description: 'TBD', closeDate: '' },
        { code: '2804', description: 'TBD', closeDate: '' },
        { code: '2805', description: 'TBD', closeDate: '' },
        { code: '2806', description: 'TBD', closeDate: '' },
        { code: '2807', description: 'TBD', closeDate: '' },
        { code: '2808', description: 'TBD', closeDate: '' },
        { code: '2809', description: 'TBD', closeDate: '' },
        { code: '2810', description: 'TBD', closeDate: '' },
        { code: '2811', description: 'TBD', closeDate: '' },
        { code: '2812', description: 'TBD', closeDate: '' },
        { code: '2813', description: 'TBD', closeDate: '' },
        { code: '2814', description: 'TBD', closeDate: '' },
        { code: '2815', description: 'TBD', closeDate: '' },
        { code: '2816', description: 'TBD', closeDate: '' },
        { code: '2817', description: 'TBD', closeDate: '' },
        { code: '2818', description: 'TBD', closeDate: '' },
        { code: '2819', description: 'TBD', closeDate: '' },
        { code: '798', description: 'TEST', closeDate: '' },
        { code: '799', description: 'TEST FLEET', closeDate: '' },
        { code: '739', description: 'TEST000009999999', closeDate: '' },
        { code: '788', description: 'TEST44444 GTF', closeDate: '' },
        { code: '810', description: 'TESTINGLOVUPDATE', closeDate: '' },
        { code: '1906', description: 'TESTRR', closeDate: '' },
        { code: '303', description: 'TIA ASSET', closeDate: '' },
        { code: '304', description: 'TPA ASSET', closeDate: '' },
        { code: '760', description: 'TREST1223', closeDate: '' },
        { code: '305', description: 'TTS ASSET', closeDate: '' },
        { code: '854', description: 'TTTTT', closeDate: '' },
        { code: '306', description: 'TUC ASSET', closeDate: '' },
        { code: '383', description: 'U2', closeDate: '' },
        { code: '721', description: 'UAS1123', closeDate: '' },
        { code: '638', description: 'UAS1234', closeDate: '' },
        { code: '802', description: 'UASTESTXXXX', closeDate: '' },
        { code: '307', description: 'UCC ASSET', closeDate: '' },
        { code: '640', description: 'UH11234', closeDate: '' },
        { code: '385', description: 'UH60', closeDate: '' },
        { code: '639', description: 'UH601234', closeDate: '' },
        { code: '3198', description: 'UJHY', closeDate: '' },
        { code: '3197', description: 'UJKI', closeDate: '' },
        { code: '1005', description: 'USVTEST1', closeDate: '' },
        { code: '3183', description: 'UUUJ', closeDate: '' },
        { code: '3194', description: 'UUY', closeDate: '' },
        { code: '3184', description: 'UYT', closeDate: '' },
        { code: '448', description: 'V-TEST', closeDate: '' },
        { code: '951', description: 'V91000', closeDate: '' },
        { code: '952', description: 'V91001', closeDate: '' },
        { code: '2139', description: 'VENDOR BE350', closeDate: '' },
        { code: '812', description: 'VESSEL TEST', closeDate: '' },
        { code: '731', description: 'VESSELASSETTEST', closeDate: '' },
        { code: '762', description: 'VESSSELTEST2', closeDate: '' },
        { code: '2159', description: 'W03761', closeDate: '' },
        { code: '2153', description: 'W04003', closeDate: '' },
        { code: '2154', description: 'W04004', closeDate: '' },
        { code: '2155', description: 'W04008', closeDate: '' },
        { code: '2170', description: 'W124001', closeDate: '' },
        { code: '2171', description: 'W124002', closeDate: '' },
        { code: '2172', description: 'W124003', closeDate: '' },
        { code: '2173', description: 'W124004', closeDate: '' },
        { code: '2174', description: 'W124005', closeDate: '' },
        { code: '2175', description: 'W124006', closeDate: '' },
        { code: '2176', description: 'W124007', closeDate: '' },
        { code: '956', description: 'W184297', closeDate: '' },
        { code: '959', description: 'W184298', closeDate: '' },
        { code: '957', description: 'W184300', closeDate: '' },
        { code: '958', description: 'W184301', closeDate: '' },
        { code: '960', description: 'W184302', closeDate: '' },
        { code: '2163', description: 'W2648', closeDate: '' },
        { code: '922', description: 'W40102', closeDate: '' },
        { code: '923', description: 'W40103', closeDate: '' },
        { code: '2157', description: 'W80002', closeDate: '' },
        { code: '2039', description: 'W80004', closeDate: '' },
        { code: '2164', description: 'W80005', closeDate: '' },
        { code: '953', description: 'W80007', closeDate: '' },
        { code: '2156', description: 'W80009', closeDate: '' },
        { code: '1900', description: 'W8001', closeDate: '' },
        { code: '2149', description: 'W80010', closeDate: '' },
        { code: '2152', description: 'W80011', closeDate: '' },
        { code: '1891', description: 'W80101', closeDate: '' },
        { code: '2148', description: 'W80102', closeDate: '' },
        { code: '2161', description: 'W80109', closeDate: '' },
        { code: '2162', description: 'W8245', closeDate: '' },
        { code: '2158', description: 'W90105', closeDate: '' },
        { code: '2160', description: 'W90108', closeDate: '' },
        { code: '1877', description: 'W90122', closeDate: '' },
        { code: '1890', description: 'W90123', closeDate: '' },
        { code: '3195', description: 'YUY', closeDate: '' },
        { code: '954', description: 'Z80134', closeDate: '' },
        { code: '955', description: 'Z80135', closeDate: '' },
        { code: '768', description: 'ZWW22', closeDate: '' },
        { code: '816', description: 'ANGULARTEST', closeDate: '' },
        { code: '222', description: 'ASO ASSET', closeDate: '' },
        { code: '834', description: 'ASSET 20', closeDate: '' },
        { code: '829', description: 'TAIL 10', closeDate: '' },
        { code: '831', description: 'TAIL 12', closeDate: '' },
        { code: '832', description: 'TAIL 121', closeDate: '' },
        { code: '833', description: 'TAIL 16', closeDate: '' },
        { code: '836', description: 'TAIL 22', closeDate: '' },
        { code: '839', description: 'TAIL 456', closeDate: '' },
        { code: '820', description: 'TAIL 5', closeDate: '' },
        { code: '821', description: 'TAIL 6', closeDate: '' },
        { code: '824', description: 'TAIL 7', closeDate: '' },
        { code: '825', description: 'TAIL 71', closeDate: '' },
        { code: '826', description: 'TAIL 8', closeDate: '' },
        { code: '827', description: 'TAIL 9', closeDate: '' },
        { code: '818', description: 'TAIL NUMBER', closeDate: '' },
        { code: '840', description: 'TAIL QQ', closeDate: '' },
        { code: '815', description: 'TAIL1', closeDate: '' },
        { code: '835', description: 'TEST VV', closeDate: '' },
        { code: '838', description: 'TRES1', closeDate: '' }
    ];

const styles = {
  propContainer: {
    width: 200,
    overflow: 'hidden',
    margin: '20px auto 0'
  },
  propToggleHeader: {
    margin: '20px auto 10px'
  }
};

const getTomisSelectRootNode = (curNode, iter, callback) => {
  const MAX_TREE_ITER = 5;
  const { parentNode, parentNode: { className } } = curNode;
  const nextIter = iter + 1;
  if (className.indexOf('Select--single') >= 0) {
    callback(curNode);
  } else if (nextIter > MAX_TREE_ITER) {
    //Prevent infinite recursion
    return undefined;
  } else {
    getTomisSelectRootNode(parentNode, nextIter, callback);
  }
};

const tableData = [
  {
    name: 'John Smith',
    status: 'Employed',
    selected: true
  },
  {
    name: 'Randal White',
    status: 'Unemployed'
  },
  {
    name: 'Stephanie Sanders',
    status: 'Employed',
    selected: true
  }
  // {
  //   name: 'Steve Brown',
  //   status: 'Employed'
  // },
  // {
  //   name: 'Joyce Whitten',
  //   status: 'Employed'
  // },
  // {
  //   name: 'Samuel Roberts',
  //   status: 'Employed'
  // },
  // {
  //   name: 'Adam Moore',
  //   status: 'Employed'
  // }
];

export default class TableEditable extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      fixedHeader: true,
      fixedFooter: false,
      stripedRows: true,
      showRowHover: true,
      selectable: false,
      multiSelectable: false,
      enableSelectAll: false,
      deselectOnClickaway: true,
      showCheckboxes: false,
      height: '500px',
      value: null,
      menuContainerStyle: { position: 'absolute', top: '0', left: '0', width: '100%' }
    };
  }

  handleToggle = (event, toggled) => {
    this.setState({
      [event.target.name]: toggled
    });
  };

  handleChange = event => {
    this.setState({ height: event.target.value });
  };

  setValue = value => {
    this.setState({ value });
    if (value) {
      console.log('Support level selected:', value.description);
    }
  };
  renderOption = option => {
    return (
      <Highlighter
        highlightClassName="lov-highlight-text"
        highlightStyle={{ backgroundColor: amber400 }}
        searchWords={[this._inputValue]}
        textToHighlight={option.description}
      />
    );
  };
  renderValue = option => {
    return <strong style={{ color: option.color }}>{option.description}</strong>;
  };

  onFoundSelectRootNode = rootNode => {
    console.log('rootNode=', rootNode);
    if (rootNode) {
      const bcr = rootNode.getBoundingClientRect();
      const { top, left, width, height } = bcr;
      this.setState({ menuContainerStyle: { position: 'fixed', top: `${top + height}px`, left, width } });
    }
  };

  onFocusSelect = evt => {
    getTomisSelectRootNode(evt.target, 0, this.onFoundSelectRootNode);
  };

  render() {
    return (
      <div>
        <Table
          height={this.state.height}
          fixedHeader={this.state.fixedHeader}
          fixedFooter={this.state.fixedFooter}
          selectable={this.state.selectable}
          multiSelectable={this.state.multiSelectable}
        >
          <TableHeader displaySelectAll={this.state.showCheckboxes} adjustForCheckbox={this.state.showCheckboxes} enableSelectAll={this.state.enableSelectAll}>
            <TableRow>
              <TableHeaderColumn tooltip="The ID">ID</TableHeaderColumn>
              <TableHeaderColumn tooltip="The Name">Name</TableHeaderColumn>
              <TableHeaderColumn tooltip="The Status">Status</TableHeaderColumn>
            </TableRow>
          </TableHeader>
          <TableBody
            displayRowCheckbox={this.state.showCheckboxes}
            deselectOnClickaway={this.state.deselectOnClickaway}
            showRowHover={this.state.showRowHover}
            stripedRows={this.state.stripedRows}
          >
            {tableData.map((row, index) => (
              <TableRow key={index} selected={row.selected}>
                <TableRowColumn>{index}</TableRowColumn>
                <TableRowColumn>
                  <div className="MaterialSelector">
                    <Select
                      labelKey="description"
                      onInputChange={inputValue => this._inputValue = inputValue}
                      options={options}
                      optionRenderer={this.renderOption}
                      onChange={this.setValue}
                      value={this.state.value}
                      valueKey="code"
                      valueRenderer={this.renderValue}
                      onFocus={this.onFocusSelect}
                      menuContainerStyle={this.state.menuContainerStyle}
                    />
                  </div>
                </TableRowColumn>
                <TableRowColumn>
                  <div className="MaterialSelector">
                    <Select
                      labelKey="description"
                      onInputChange={inputValue => this._inputValue = inputValue}
                      options={options}
                      optionRenderer={this.renderOption}
                      onChange={this.setValue}
                      value={this.state.value}
                      valueKey="code"
                      valueRenderer={this.renderValue}
                      onFocus={this.onFocusSelect}
                      menuContainerStyle={this.state.menuContainerStyle}
                    />
                  </div>
                </TableRowColumn>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
    );
  }
}
